package Model.SkillTable;
// Generated 2016/02/29 8:27:58 by Hibernate Tools 4.3.1



/**
 * SkillTableId generated by hbm2java
 */
public class SkillTableId  implements java.io.Serializable {


     private int nameId;
     private int skillId;

    public SkillTableId() {
    }

    public SkillTableId(int nameId, int skillId) {
       this.nameId = nameId;
       this.skillId = skillId;
    }
   
    public int getNameId() {
        return this.nameId;
    }
    
    public void setNameId(int nameId) {
        this.nameId = nameId;
    }
    public int getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(int skillId) {
        this.skillId = skillId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SkillTableId) ) return false;
		 SkillTableId castOther = ( SkillTableId ) other; 
         
		 return (this.getNameId()==castOther.getNameId())
 && (this.getSkillId()==castOther.getSkillId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNameId();
         result = 37 * result + this.getSkillId();
         return result;
   }   


}


